# Generated by Django 5.1.3 on 2025-05-22 18:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_node', models.CharField(max_length=100)),
                ('end_node', models.CharField(max_length=100)),
                ('polyline', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), help_text='List of coordinates as JSON: [{lat: ..., lng: ...}, ...]', size=None, verbose_name='Polyline Coordinates')),
            ],
        ),
    ]
